version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: trading_bot_mongodb
    env_file:
      - ./config/.env
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secure_password
      MONGO_INITDB_DATABASE: trading_db
    ports:
      - "27017:27017"
    volumes:
      - ./docker/mongodb/data:/data/db
      - ./docker/mongodb/init:/docker-entrypoint-initdb.d
    networks:
      - trading_network
    restart: unless-stopped
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s

  mongo_express:
    image: mongo-express:latest
    container_name: trading_bot_mongo_express
    env_file:
      - ./config/.env
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: secure_password
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: secure_password
    ports:
      - "8081:8081"
    networks:
      - trading_network
    depends_on:
      - mongodb
    restart: unless-stopped

networks:
  trading_network:
    driver: bridge
